/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.melvin.clase02.vista;
import ClsOperacionesMat.ClsOperacionesMat;
/**
 *
 * @author recin
 */
public class VistaCal extends javax.swing.JFrame {

    /**
     * Creates new form VistaCal
     */
    public VistaCal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDato1 = new javax.swing.JTextField();
        Dato = new javax.swing.JLabel();
        DAto = new javax.swing.JLabel();
        txtR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDato2 = new javax.swing.JTextField();
        btmCalcular = new javax.swing.JButton();
        btmResta = new javax.swing.JButton();
        btmDivison = new javax.swing.JButton();
        btmMultiplicacion = new javax.swing.JButton();
        btnAns = new javax.swing.JButton();
        btnAnsMenos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Dato.setText("DATO 1");

        DAto.setText("DATO 2");

        txtR.setEditable(false);
        txtR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRActionPerformed(evt);
            }
        });

        jLabel4.setText("RESULTADO");

        txtDato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDato2ActionPerformed(evt);
            }
        });

        btmCalcular.setText("Sumar");
        btmCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCalcularActionPerformed(evt);
            }
        });

        btmResta.setText("Resta");
        btmResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRestaActionPerformed(evt);
            }
        });

        btmDivison.setText("Division");
        btmDivison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmDivisonActionPerformed(evt);
            }
        });

        btmMultiplicacion.setText("Multiplicacion");
        btmMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmMultiplicacionActionPerformed(evt);
            }
        });

        btnAns.setText("Ans+");
        btnAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnsActionPerformed(evt);
            }
        });

        btnAnsMenos.setText("Ans-");
        btnAnsMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnsMenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(Dato))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(txtDato1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDato2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(DAto)
                        .addGap(152, 152, 152))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btmCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btmResta)
                        .addGap(49, 49, 49)
                        .addComponent(btmDivison)
                        .addGap(62, 62, 62)
                        .addComponent(btmMultiplicacion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(46, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtR, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAns, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(btnAnsMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)))))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dato)
                    .addComponent(DAto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmCalcular)
                    .addComponent(btmResta)
                    .addComponent(btmDivison)
                    .addComponent(btmMultiplicacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAns)
                    .addComponent(btnAnsMenos))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setText("CALCULADORA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDato2ActionPerformed

    private void txtRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRActionPerformed

    private void btmCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCalcularActionPerformed
        Double Dato1 = Double.parseDouble(txtDato1.getText());
        Double Dato2 = Double.parseDouble(txtDato2.getText());
        
        ClsOperacionesMat Suma = new ClsOperacionesMat();
        Double r = Dato1 + Dato2;
        txtR.setText(r.toString());
                         
//        txtR.setText(txtDato1.getText() + txtDato2.getText());
    }//GEN-LAST:event_btmCalcularActionPerformed

    private void btmRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRestaActionPerformed
        Double Dato1 = Double.parseDouble(txtDato1.getText());
        Double Dato2 = Double.parseDouble(txtDato2.getText());
        ClsOperacionesMat Resta = new ClsOperacionesMat();
        Double r = Dato1 - Dato2;
        txtR.setText(r.toString());
    }//GEN-LAST:event_btmRestaActionPerformed

    private void btmDivisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmDivisonActionPerformed
         Double Dato1 = Double.parseDouble(txtDato1.getText());
        Double Dato2 = Double.parseDouble(txtDato2.getText());
        ClsOperacionesMat Division = new ClsOperacionesMat();
        Double r = Dato1 / Dato2;
        txtR.setText(r.toString());
    }//GEN-LAST:event_btmDivisonActionPerformed

    private void btmMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmMultiplicacionActionPerformed
        Double Dato1 = Double.parseDouble(txtDato1.getText());
        Double Dato2 = Double.parseDouble(txtDato2.getText());
        
        ClsOperacionesMat Multiplicacion = new ClsOperacionesMat();
        Double r = Dato1 * Dato2;
        txtR.setText(r.toString());
    }//GEN-LAST:event_btmMultiplicacionActionPerformed
        Double r1 = 0.0;
    private void btnAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnsActionPerformed
        Double Dato1 = Double.parseDouble(txtDato1.getText());
        Double Dato2 = Double.parseDouble(txtDato2.getText());
        
        ClsOperacionesMat sumar = new ClsOperacionesMat ();
        sumar.setDato1(Dato1);
        sumar.setDato2(Dato2);
        
        Double r = sumar.Suma();
        this.r1 += r;
        
        txtR.setText(this.r1.toString());
    }//GEN-LAST:event_btnAnsActionPerformed

    private void btnAnsMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnsMenosActionPerformed
        Double Dato1 = Double.parseDouble(txtDato1.getText());
        Double Dato2 = Double.parseDouble(txtDato2.getText());
        
        ClsOperacionesMat restar = new ClsOperacionesMat();
        restar.setDato1(Dato1);
        restar.setDato2(Dato2);
        
        Double r = restar.Resta();
        this.r1 -= r;
        
        txtR.setText(this.r1.toString());        
    }//GEN-LAST:event_btnAnsMenosActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DAto;
    private javax.swing.JLabel Dato;
    private javax.swing.JButton btmCalcular;
    private javax.swing.JButton btmDivison;
    private javax.swing.JButton btmMultiplicacion;
    private javax.swing.JButton btmResta;
    private javax.swing.JButton btnAns;
    private javax.swing.JButton btnAnsMenos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDato1;
    private javax.swing.JTextField txtDato2;
    private javax.swing.JTextField txtR;
    // End of variables declaration//GEN-END:variables
}
